package io.delta.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-03T00:38:17.624+01:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "Api", 
                  wsdlLocation = "file:/D:/HOME/SerializationDemos/ClientServerProtoSample/java/pb-server/WebContent/Api.wsdl",
                  targetNamespace = "http://www.delta.io/Api/") 
public class Api_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.delta.io/Api/", "Api");
    public final static QName ApiSOAP = new QName("http://www.delta.io/Api/", "ApiSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/HOME/SerializationDemos/ClientServerProtoSample/java/pb-server/WebContent/Api.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Api_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/HOME/SerializationDemos/ClientServerProtoSample/java/pb-server/WebContent/Api.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Api_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Api_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Api_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Api_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Api_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public Api_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiSOAP")
    public Api getApiSOAP() {
        return super.getPort(ApiSOAP, Api.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Api
     */
    @WebEndpoint(name = "ApiSOAP")
    public Api getApiSOAP(WebServiceFeature... features) {
        return super.getPort(ApiSOAP, Api.class, features);
    }

}
