/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package io.delta.api;

import io.delta.proto.generated.ProtobufCity.City;
import io.delta.proto.generated.ProtobufCity.CityCollection;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.mail.util.ByteArrayDataSource;

/**
 * This class was generated by Apache CXF 3.0.4 2015-03-03T00:38:17.577+01:00
 * Generated source version: 3.0.4
 * 
 */

@javax.jws.WebService(serviceName = "Api", portName = "ApiSOAP", targetNamespace = "http://www.delta.io/Api/", wsdlLocation = "file:/D:/HOME/SerializationDemos/ClientServerProtoSample/java/pb-server/WebContent/Api.wsdl", endpointInterface = "io.delta.api.Api")
public class ApiImpl implements Api {

	private static final Logger LOG = Logger.getLogger(ApiImpl.class.getName());

	/*
	 * (non-Javadoc)
	 * 
	 * @see io.delta.api.Api#searchCities(io.delta.api.SearchCitiesRequest
	 * parameters )*
	 */
	public io.delta.api.SearchCitiesResponse searchCities(SearchCitiesRequest parameters) {
		LOG.info("Executing operation searchCities");
		System.out.println(parameters);
		try {
			io.delta.api.SearchCitiesResponse _return = new io.delta.api.SearchCitiesResponse();
			DataSource ds = new ByteArrayDataSource(retrieveAllCities(), "application/octet-stream");
			javax.activation.DataHandler _returnOut = new DataHandler(ds);
			_return.setOut(_returnOut);
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	private byte[] retrieveAllCities() {

		// Build the list of cities
		List<City> cities = new ArrayList<City>();

		cities.add(City.newBuilder().setId(1L).setName("Paris").setCountryCode("FRA").setEnabled(true).build());
		cities.add(City.newBuilder().setId(2L).setName("Lyon").setCountryCode("FRA").setEnabled(true).setDisplayOrder(1).build());
		cities.add(City.newBuilder().setId(3L).setName("Marseille").setCountryCode("FRA").setEnabled(true).build());

		CityCollection.Builder builder = CityCollection.newBuilder().addAllItems(cities);

		CityCollection collection = builder.build();
		return collection.toByteArray();
	}
}
