//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtobufClient.ApiServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.delta.io/Api/", ConfigurationName="ApiServiceReference.Api")]
    public interface Api {
        
        // CODEGEN: Generating message contract since the wrapper name (searchCitiesRequest) of message searchCitiesRequest does not match the default value (searchCities)
        [System.ServiceModel.OperationContractAttribute(Action="http://www.delta.io/Api/searchCities", ReplyAction="*")]
        global::ProtobufClient.ApiServiceReference.searchCitiesResponse searchCities(global::ProtobufClient.ApiServiceReference.searchCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.delta.io/Api/searchCities", ReplyAction="*")]
        System.Threading.Tasks.Task<global::ProtobufClient.ApiServiceReference.searchCitiesResponse> searchCitiesAsync(global::ProtobufClient.ApiServiceReference.searchCitiesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchCitiesRequest", WrapperNamespace="http://www.delta.io/Api/", IsWrapped=true)]
    public partial class searchCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @in;
        
        public searchCitiesRequest() {
        }
        
        public searchCitiesRequest(byte[] @in) {
            this.@in = @in;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchCitiesResponse", WrapperNamespace="http://www.delta.io/Api/", IsWrapped=true)]
    public partial class searchCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @out;
        
        public searchCitiesResponse() {
        }
        
        public searchCitiesResponse(byte[] @out) {
            this.@out = @out;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiChannel : global::ProtobufClient.ApiServiceReference.Api, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiClient : System.ServiceModel.ClientBase<global::ProtobufClient.ApiServiceReference.Api>, global::ProtobufClient.ApiServiceReference.Api {
        
        public ApiClient() {
        }
        
        public ApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ProtobufClient.ApiServiceReference.searchCitiesResponse global::ProtobufClient.ApiServiceReference.Api.searchCities(global::ProtobufClient.ApiServiceReference.searchCitiesRequest request) {
            return base.Channel.searchCities(request);
        }
        
        public byte[] searchCities(byte[] @in) {
            global::ProtobufClient.ApiServiceReference.searchCitiesRequest inValue = new global::ProtobufClient.ApiServiceReference.searchCitiesRequest();
            inValue.@in = @in;
            global::ProtobufClient.ApiServiceReference.searchCitiesResponse retVal = ((global::ProtobufClient.ApiServiceReference.Api)(this)).searchCities(inValue);
            return retVal.@out;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<global::ProtobufClient.ApiServiceReference.searchCitiesResponse> global::ProtobufClient.ApiServiceReference.Api.searchCitiesAsync(global::ProtobufClient.ApiServiceReference.searchCitiesRequest request) {
            return base.Channel.searchCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<global::ProtobufClient.ApiServiceReference.searchCitiesResponse> searchCitiesAsync(byte[] @in) {
            global::ProtobufClient.ApiServiceReference.searchCitiesRequest inValue = new global::ProtobufClient.ApiServiceReference.searchCitiesRequest();
            inValue.@in = @in;
            return ((global::ProtobufClient.ApiServiceReference.Api)(this)).searchCitiesAsync(inValue);
        }
    }
}
